# ==============================================================================
# SonarQube Project Configuration
# Repo   : core-cloud-workflow-maven-docker-actions
# Ticket : CCL-6306
# ==============================================================================

sonar.projectKey=UKHomeOffice_core-cloud-workflow-maven-docker-actions
sonar.projectName=core-cloud-workflow-maven-docker-actions
sonar.projectVersion=1.0

# Source and test paths
sonar.sources=tests/dummy-service/src/main/java
sonar.tests=tests/dummy-service/src/test/java
sonar.java.binaries=tests/dummy-service/target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions – do not analyse generated code or build output
sonar.exclusions=**/target/**,**/.github/**,**/scripts/**
# sonar.exclusions=**/target/**,**/node_modules/**,**/.git/**,**/checkov-results.sarif/**

# Coverage
sonar.coverage.jacoco.xmlReportPaths=tests/dummy-service/target/site/jacoco/jacoco.xml
